### ISSUE TITLE
CSS not served properly with gorouter

### ISSUE THREAD

**Issue by troytop** [Stackato-Apps/node-env#5]
Still works fine on Stackato, but if you run this app on CF instances using the gorouter, you run into this issue:
https://github.com/cloudfoundry/gorouter/issues/62

I worked around this in another app by explicitly setting the Content-Type for .css files:

https://github.com/gazsam/DoggyAdoption/commit/939b5d0e7bfb1d14e5cb26e0f5eba3c8fd0578bb

Couldn't get this working myself with node-env though.

While you're in there, note that `path.exists` is gone from recent versions of node.js, so some future-proofing might be in order. https://stackoverflow.com/questions/4482686/check-synchronously-if-file-directory-exists-in-node-js

**Comment by btat** [comment]
Closed by https://github.com/Stackato-Apps/node-env/pull/6
